/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Splash;

import my.estadistico.Menu;



/**
 *
 * @author werner_pc
 */
public class SplashCreem extends javax.swing.JFrame implements Runnable {

    private Thread Hilo;
    /**
     * Creates new form Determinante2x2
     */
    public SplashCreem() {
       new Transparencia().TransCompFrame(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(212, 103, 102));
        jProgressBar1.setFont(new java.awt.Font("Acid", 3, 24)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(126, 205, 180));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 490, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/LOGO ESTADISTICO 2.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 680, 522));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    new Hilo(jProgressBar1).start();    
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

public void run(){
    try{
        this.setLocationRelativeTo(null);
       
        this.setVisible(true);
        this.Hilo.sleep(6000);
        this.setLocation(300, 300);
        this.dispose();
        Menu m = new Menu();
        m.setVisible(true);
        

        
    }catch(Exception e){
        
    }  
}
}