/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.estadistico;

/**
 *
 * @author werner
 */
public class Muestra extends javax.swing.JInternalFrame {

    /**
     * Creates new form Muestra
     */
    public Muestra() {
        initComponents();
    }
    
    public Double N; //Poblacion
    public Double k; //Nivel de Confianza
    public Double e; //Error muestral
    public Double p; //proporción de individuos que poseen en la población la característica de estudio
    public Double q; //es la proporción de individuos que no poseen esa característica, es decir, es 1-p
    
    
    public Double resultado;
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtErrorMuestral = new javax.swing.JTextField();
        txtMostrar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProporcionDeIndividuosQueSiPosee = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtProparcionDeIndividuosQueNoPosee = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtConfianza = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setMaximizable(true);
        setToolTipText("");
        setAutoscrolls(true);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1358, 652));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tamaño de la Población =  N");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 39, -1, -1));

        jLabel2.setText("Error Muestral Deseado = e");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 59, -1, -1));

        jLabel3.setText("Constante que indica el nivel de confianza = k");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 79, -1, -1));
        getContentPane().add(txtPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 124, 110, -1));

        jLabel4.setText("N");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 127, -1, -1));

        jLabel5.setText("e");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 14, -1));
        getContentPane().add(txtErrorMuestral, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));
        getContentPane().add(txtMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 86, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel6.setText("k");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 14, -1));

        jLabel7.setText("p");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 15, -1));
        getContentPane().add(txtProporcionDeIndividuosQueSiPosee, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        jLabel8.setText("q");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 20, -1));
        getContentPane().add(txtProparcionDeIndividuosQueNoPosee, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));

        jLabel9.setText("n =");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 20, 20));
        getContentPane().add(txtConfianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/fondosplash.PNG"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 640, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.N = Double.parseDouble(this.txtPoblacion.getText());
         this.k = Double.parseDouble(this.txtConfianza.getText());
         this.e = Double.parseDouble(this.txtErrorMuestral.getText());
         this.p = Double.parseDouble(this.txtProporcionDeIndividuosQueSiPosee.getText());
         this.q = Double.parseDouble(this.txtProparcionDeIndividuosQueNoPosee.getText());
          this.operacion();
          this.txtMostrar.setText(this.resultado.toString());
          
          
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    public void operacion(){
         resultado = (k*k*p*q*N)/((e*e*(N-1))+(k*k*p*q));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtConfianza;
    private javax.swing.JTextField txtErrorMuestral;
    private javax.swing.JTextField txtMostrar;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtProparcionDeIndividuosQueNoPosee;
    private javax.swing.JTextField txtProporcionDeIndividuosQueSiPosee;
    // End of variables declaration//GEN-END:variables
}
