/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.estadistico;

/**
 *
 * @author USUARIO
 */
public class Ventana extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();


        
        botonWeb1 = new botones.BotonWeb();
        botonWeb2 = new botones.BotonWeb();
        botonWeb3 = new botones.BotonWeb();
        splash = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1358, 652));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonWeb1.setBackground(new java.awt.Color(255, 51, 153));
        botonWeb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/soportetecnico.png"))); // NOI18N
        botonWeb1.setLink("http://www.estadistico10.pe.hu");
        getContentPane().add(botonWeb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 442, 120));

        botonWeb2.setBackground(new java.awt.Color(255, 51, 153));
        botonWeb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quienessomos.png"))); // NOI18N
        botonWeb2.setLink("http://www.estadistico10.pe.hu");
        getContentPane().add(botonWeb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 442, 130));

        botonWeb3.setBackground(new java.awt.Color(255, 51, 102));
        botonWeb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/errorreportar.png"))); // NOI18N
        botonWeb3.setLink("http://www.estadistico10.pe.hu");
        getContentPane().add(botonWeb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, 442, 120));

        splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/fondosplash.PNG"))); // NOI18N
        getContentPane().add(splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 710, 470));

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonWeb1 = new botones.BotonWeb();
        botonWeb2 = new botones.BotonWeb();
        botonWeb3 = new botones.BotonWeb();
        splash = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1358, 652));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonWeb1.setBackground(new java.awt.Color(255, 51, 153));
        botonWeb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/soportetecnico.png"))); // NOI18N
        botonWeb1.setLink("http://www.twitter.com");
        getContentPane().add(botonWeb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 442, 120));

        botonWeb2.setBackground(new java.awt.Color(255, 51, 153));
        botonWeb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quienessomos.png"))); // NOI18N
        botonWeb2.setLink("http://www.facebook.com");
        getContentPane().add(botonWeb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 137, 442, 130));

        botonWeb3.setBackground(new java.awt.Color(255, 51, 102));
        botonWeb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/errorreportar.png"))); // NOI18N
        botonWeb3.setLink("http://www.youtube.com");
        getContentPane().add(botonWeb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, 442, 120));

        splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/fondosplash.PNG"))); // NOI18N
        getContentPane().add(splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 710, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
              

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private botones.BotonWeb botonWeb1;
    private botones.BotonWeb botonWeb2;
    private botones.BotonWeb botonWeb3;
    private javax.swing.JLabel splash;
    // End of variables declaration//GEN-END:variables
}
