package BaseDatos;


import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Werner
 */
public class EstudioEstadistico extends javax.swing.JFrame {

    /**
     * Creates new form EstudioEstadistico
     */
    public EstudioEstadistico() {
        initComponents();
        this.obtenerCodigo();
        this.ComboBox();
        
   
    }
     Parametros p = new Parametros();
     Tabla t = new Tabla();
     
     public String usuario;
     Integer codigo=0; //Codigo del usuario
     String NombreEE;
     

     /*
     Se obtiene el codigo de usuario
     */
    public void ObtenerUsuario(String usuario) {
        this.usuario= usuario;
    }
     
    /*
    Obtenemos el codigo del usuario
    */
    
    private void ComboBox(){
    try{
        String sql="SELECT * FROM estudio where Usuario_Cod_Usuario='"+codigo+"'";
        p.prepararConexion(sql);
        p.ejecutar();
        
        while(p.rs.next()){
            String nombre = p.rs.getString("nombre_DelEstudio");
            this.jComboBox1.addItem(nombre);
        }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }
    
  
    
    public void obtenerCodigo(){
  
        String sql="SELECT Cod_Usuario FROM estadistica.usuario where Nombre='"+this.usuario+"'";
        try{
              p.prepararConexion(sql);
              p.ejecutar();
              if(p.rs.next()){
                  Integer cod = p.rs.getInt("Cod_Usuario");
                  this.codigo=cod;
                      
              }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
        
    
}//Finaliza metodo para obtener el codigo del usuario
    
    /*
    Obtenemos el codigo del usuario
    */
     public void ObterCodigoEE(){
          String varCombo = (String)this.jComboBox1.getSelectedItem();
        String sql="SELECT * FROM estudio where nombre_DelEstudio=?";
        try{
              p.prepararConexion(sql);
              p.pst.setString(1, varCombo);
              p.ejecutar();
              if(p.rs.next()){
                  Integer cod = p.rs.getInt("cod_Estudio");
                  this.jTextField1.setText(cod.toString());
           
                  t.ObtenerCodigoEE(cod);
                  t.setVisible(true);
                 
              }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
     }//Finaliza metodo para obtener codigo EE
    
    /*
    Obtenemos los datos de los Texfield
    */
    private void obtenerDatos(){
    this.NombreEE=this.jTextField1.getText();
}//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre del estudio");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Estudios Almacenados");

        jButton2.setText("Mostrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox1, 0, 130, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addComponent(jButton2)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.obtenerCodigo();
//Obtiene el codigo del usuario
this.obtenerDatos();//Obtiene el nombre del estudio del texfield

        try{
    
            String sql= "INSERT INTO estudio (Usuario_Cod_Usuario, nombre_DelEstudio) VALUES ('"+this.codigo+"', '"+this.NombreEE+"')";
            
            
            p.prepararConexion(sql);
            p.pst.execute();
            JOptionPane.showMessageDialog(null, "Se a creado correctamente");
             
             t.ObtenerNombreEE(this.NombreEE);
             t.ObtenerCodigo(this.codigo);//Envia el codigo de usuario a la tabla
             t.setVisible(true);
        
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
       
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.obtenerCodigo();
this.ComboBox();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
this.ObterCodigoEE();
            
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudioEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudioEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudioEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudioEstadistico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudioEstadistico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
